name: Deploy Assets Server

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - dev
          - local
          - staging
          - qa
          - next
          - live
        description: Environment to deploy assets server to
        required: true

jobs:
  DeployAssetsServer:
    runs-on: ubuntu-latest
    steps:
      - name: Set workflow variables based on env
        id: vars
        run: |
          case dev in
          local) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-local ;;
          dev) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-dev ;;
          staging) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-staging ;;
          qa) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-qa ;;
          next) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference-next ;;
          live) echo "##[set-output name=DEPLOYMENT_PROJECT;]remo-conference ;;
          *) echo "Invalid environment" && exit 1 ;;
          esac

          ENVIRONMENT=$(echo ${{ github.event.inputs.environment }} | tr '[:lower:]' '[:upper:]')
          echo "##[set-output name=GOOGLE_CLOUD_KEY;]$(echo GCLOUD_ENC_KEY_$ENVIRONMENT)"


      - name: Deploying Assets Server to ${{ steps.vars.outputs.DEPLOYMENT_PROJECT }}
        run: |
          echo ${{ steps.vars.outputs.GOOGLE_CLOUD_KEY }}
          echo ${{ steps.vars.outputs.DEPLOYMENT_PROJECT }}
